const projects=[
    {
        id:1,
        name:"Workcattion",
        serial:"249df660",
        location:"production",
        timeframe:"1h"
    },
    {
        id:2,
        name:"Kitetail",
        serial:"2249df008",
        location:"staging",
        timeframe:"3h"
    },
    {
        id:3,
        name:"Workcation",
        serial:"216644642",
        location:"staging",
        timeframe:"12h"
    },
    {
        id:4,
        name:"Easywire",
        serial:"dad288595",
        location:"production",
        timeframe:"2d"
    },
    {
        id:5,
        name:"Easywire",
        serial:"624be94c",
        location:"production",
        timeframe:"5d"
    },
    {
        id:6,
        name:"Workcation",
        serial:"e115f80e",
        location:"production",
        timeframe:"1w"
    },
    {
        id:7,
        name:"Resumaid",
        serial:"5e1134ed0",
        location:"staging",
        timeframe:"1w"
    },
]

export default projects